services:
  tdengine:
    image: tdengine/tdengine:3.3.2.0
    container_name: tdengine
    volumes:
      - ~/data/taos/dnode/data:/var/lib/taos
      - ~/data/taos/dnode/log:/var/log/taos
    ports:
      - "6030:6030"
      - "6041:6041"
      - "6043-6060:6043-6060"
      - "6043-6060:6043-6060/udp"
    restart: always
