version: '3'
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "google@google.com"
      ZO_ROOT_USER_PASSWORD: "L12sXy8d"
    ports:
      - "5081:5080"
    volumes:
      - data:/data

volumes:
  data: