services:
  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://root:root@xxxxxxx/mattermost?sslmode=disable&connect_timeout=10
    ports:
      - 8065:8065
